title: Joseph Wagner # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bonjour, my name is Joseph Wagner and I am a Sophomore at Tulane University.
  <br> I am currently pursuing a Bachelor's degree in Math and Computer Science.
  <br> Since March 2021, I have been a software engineering intern for a dating
  <br> app startup Revibe. As for computer science education, I am well-versed in:
  1. Java
  2. C
  3. C++
  4. OpenGL
  5. Python
  6. HTML/CSS
  <br><br>
  <a href="https://www.linkedin.com/in/joseph-wagner-323825209/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
